mypollsite/mypollsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('',include('poll.urls')),
]

mypollsite/poll/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns=[
    path('',views.IndexView.as_view(),name='home'),
    path('detail/<str:pk>/',views.DetailView.as_view(),name='detail'),    
    path('vote/<str:pk>/',views.Vote,name='vote'),
    path('result/<str:pk>/',views.ResultView.as_view(),name='result'),
    path('authentication/',views.Authenticate,name='authenticate'),
    path('login/',views.login,name='login'),
    path('add_question/',views.Add_question.as_view(),name='add_question'),
    path('signup/',views.SignUp,name='sign_up_form'),
    path('registration/',views.Registration,name='registration'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/profile/',views.Profile,name='profile'),
    path('signout/',views.signout,name='sign-out'),
]

mypollsite/poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question=models.CharField(max_length=300,blank=False)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return self.question
class Choices(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choices=models.CharField(max_length=200,blank=False)
    updated=models.DateTimeField(auto_now=True)  
    votes=models.IntegerField(default=0)  
    def __str__(self) -> str:
        return self.choices

mypollsite/poll/forms.py
from django import forms
from .models import Question,Choices

class QuestionForm(forms.ModelForm):
    choices=forms.CharField(max_length=200,help_text='Type your choices for the poll separated by commas',
                            label='Choices')
    class Meta:
        model=Question
        fields=['question']
    def save(self, commit=True):
        question=super().save(commit=False)
        if commit:
            question.save()
            choices_text=self.cleaned_data['choices']
            choices_list=[choice.strip() for choice in choices_text.split(',')]
            for choices_text in choices_list:
                Choices.objects.create(question=question,choices=choices_text)
        return question

mypollsite/poll/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from .models import Question,Choices
from django.db.models import F
from django.views import generic
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import QuestionForm
from django.urls import reverse_lazy,reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.

# Home View:
class IndexView(generic.ListView):
    template_name='poll/index.html'
    context_object_name='question_posted'
    def get_queryset(self) -> QuerySet[Any]:
        return Question.objects.order_by('-question')
# Poll View:
class DetailView(generic.DetailView):
    model=Question
    template_name='poll/detail.html'
# Voting Logic:
def Vote(request,pk):
   question = get_object_or_404(Question, pk=pk)
   if request.method == 'POST':
        selected_choice_id = request.POST.get('choice')
        selected_choice = get_object_or_404(Choices, pk=selected_choice_id)
        selected_choice.votes += 1
        selected_choice.save()

        return redirect('result', pk=question.pk)

   return HttpResponse("Invalid request")
# Voting Result view:
class ResultView(generic.DetailView):
    model=Question
    template_name='poll/result.html'


def Login(request):
    global user
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            msg=messages.add_message(request,messages.ERROR,'Invalid Email or Password')
            return render(request,'poll/login.html')
    else:
        return redirect('home')
# Add Question Form:
@method_decorator(login_required, name='dispatch')
class Add_question(generic.FormView):
    template_name = 'poll/question_form.html'
    form_class = QuestionForm
    success_url = reverse_lazy('home')
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

def Authenticate(request):
    return render(request,'poll/login.html')
def SignUp(request):
    return render(request,'poll/sign_up.html')
def Registration(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')


        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exists. Please choose a different username.')
            return redirect('registration')
        user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name,
                                        last_name=last_name)
        user.save()
        return redirect('login')
    else:
        return redirect('add_question')
def Profile(request):
   return redirect('home')

def signout(request):
    messages.add_message(request,level=messages.INFO,message=f'logged out !')
    logout(request)
    return redirect('home')

mypollsite/poll/templates/poll/detail.html
{%load static%}
<head>
    <link rel="stylesheet" href="{% static 'poll/basestyle.css' %}">
</head>
<body>
    <nav><a href="{%url 'home' %}">HOME</a> <a href="/admin">ADMIN</a>{%if user.is_authenticated%}<a href="{%url 'sign-out' %}">LOG OUT</a> </nav>{%else%}<nav><a href="{%url 'authenticate' %}">LOG IN</a> </nav>{%endif%}
    <form action="{%url 'vote' pk=question.id %}" method="post">
        {%csrf_token%}
        <legend><h2>{{question.question}}</h2></legend>
        {% for choice in question.choices_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{forloop.counter}}">{{choice.choices}}</label>

        {%endfor%}
        <input type="submit" value="Vote">
    </form>
</body>

mypollsite/poll/templates/poll/index.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>

    <link rel="stylesheet" href="{% static 'poll/style.css' %}">
    <title>Poll</title>
</head>
<body>
    <nav><a href="{%url 'home' %}">HOME</a> <a href="/admin">ADMIN</a>
        {%if user.is_authenticated%}
        <a href="{%url 'sign-out' %}">LOG OUT</a> </nav>
        {%else%}<nav><a href="{%url 'authenticate' %}">LOG IN</a> </nav>
        {%endif%}

    {%for message in messages%}
        <div class="one-time-message">{{ message }}</div>
    {%endfor%}
    <h1 class="Title_of_page">Question Posted for polls :</h1>

   {%for question in question_posted%}
    <div class="to_details">
        <h4><a href="{%url 'detail' question.id %}">{{question}}</a></h4>
    </div>
   {%endfor%}
    <h2><a href="{%url 'add_question'%}">Click to add more</a></h2>
</body>
</html>

mypollsite/poll/templates/poll/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Log In</title>
    <link rel="stylesheet" href="{%static 'poll/style_login.css' %}">
</head>
<body>
    <nav><a href="{%url 'home' %}">HOME</a> <a href="/admin">ADMIN</a>{%if user.is_authenticated%}% <a href="{%url 'sign-out' %}">LOG OUT</a> </nav>{%else%}<nav><a href="{%url 'authenticate' %}">LOG IN</a> </nav>{%endif%}
    <form method="post" action="{%url 'login' %}">
        {%csrf_token%}
        <label>UserName:</label><br>
        <input type="text" name="username"><br>
        <label>Password:</label><br>
        <input type="password" name="password" ><br>
        <input type="submit" value="Log In">
    </form>
    <h3><a href="{%url 'sign_up_form' %}">Sign Up</a></h3>
</body>
</html>

mypollsite/poll/templates/poll/question_form.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'poll/style_add_question.css'%}">
</head>
<body>
    <nav><a href="{%url 'home' %}">HOME</a> <a href="/admin">ADMIN</a>{%if user.is_authenticated%}% <a href="{%url 'sign-out' %}">LOG OUT</a> </nav>{%else%}<nav><a href="{%url 'authenticate' %}">LOG IN</a> </nav>{%endif%}
    <form method="post" enctype="multipart/form-data" >
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="add" >
    </form>

</body>
</html>

mypollsite/poll/templates/poll/result.html
<head>
{% load static %}
    <link rel="stylesheet" href="{%static 'poll/resultstyle.css' %}">
</head>
<body>
    <nav><a href="{%url 'home' %}">HOME</a> <a href="/admin">ADMIN</a>{%if user.is_authenticated%} <a href="{%url 'sign-out' %}">LOG OUT</a> </nav>{%else%}<nav><a href="{%url 'authenticate' %}">LOG IN</a> </nav>{%endif%}
    <h1>{{ question.question }}</h1>

    <ul>
    {% for choice in question.choices_set.all %}
        <li>{{ choice.choices }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'detail' question.id %}">Vote again?</a>
</body>

mypollsite/poll/templates/poll/sign_up.html
<!DOCTYPE html>
<html lang="en">
{%load static%}
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'poll/stylesign_up.css' %}">
</head>
<body>
    <nav><a href="{%url 'home' %}">HOME</a> <a href="/admin">ADMIN</a>{%if user.is_authenticated%}% <a href="{%url 'sign-out' %}">LOG OUT</a> </nav>{%else%}<nav><a href="{%url 'authenticate' %}">LOG IN</a> </nav>{%endif%}
    <form action="{% url 'registration' %}" method="post">
        {%csrf_token%}
        <label>First Name:</label><br>
        <input type="text" name="first_name"><br>
        <label>Last Name:</label><br>
        <input type="text" name="last_name"><br>
        <label>User Name:</label><br>
        <input type="text" name="username"><br>
        <label>Email:</label><br>
        <input type="email" name="email"><br>
        <label>Password:</label><br>
        <input type="password" name="password"><br>
        <label>Confirm Password:</label><br>
        <input type="password">
        <input type="submit"  value="Sign Up" name="Sign Up">
    </form>
</body>
</html>